type Error {
  message: String!
}

union Result = User | Error

type Query {
  # Users
  getUser: User
  getUsers: [User]

  # Items
  getItems: [Item]
  getItem(itemID: ID!): Item
  getPannelItems(pannelID: ID!): [Item]

  # Projects
  getProject(projectID: ID!): Project
  getProjects: [Project]
}

type Mutation {
  # Users
  signUp(username: String!, email: String!, password: String!): Result
  login(username: String!, password: String!): Result

  # Projects
  addProject(title: String!, ownerID: ID!): Project
  updateProject(projectID: ID!, update: ProjectUpdate): Project

  # Items
  addItem(
    title: String!
    description: String
    position: Int!
    pannelID: ID!
  ): Item
  updateItem(itemID: ID!, update: ItemUpdate): Item
}
